PROJECT_PRN211/Cake/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cake.Models;

namespace Cake.Controllers
{
    public class BlogsController : Controller
    {
        private readonly BakeryCakeContext _context;

        public BlogsController(BakeryCakeContext context)
        {
            _context = context;
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            var bakeryCakeContext = _context.Blogs.Include(b => b.CreateByNavigation);
            return View(await bakeryCakeContext.ToListAsync());
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.CreateByNavigation)
                .FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        public IActionResult Create()
        {
            ViewData["CreateBy"] = new SelectList(_context.Users, "UserId", "UserId");
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogId,BlogTitle,Description,CreateBy,CreateDate")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CreateBy"] = new SelectList(_context.Users, "UserId", "UserId", blog.CreateBy);
            return View(blog);
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            ViewData["CreateBy"] = new SelectList(_context.Users, "UserId", "UserId", blog.CreateBy);
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BlogId,BlogTitle,Description,CreateBy,CreateDate")] Blog blog)
        {
            if (id != blog.BlogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.BlogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CreateBy"] = new SelectList(_context.Users, "UserId", "UserId", blog.CreateBy);
            return View(blog);
        }

        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.CreateByNavigation)
                .FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Blogs == null)
            {
                return Problem("Entity set 'BakeryCakeContext.Blogs'  is null.");
            }
            var blog = await _context.Blogs.FindAsync(id);
            if (blog != null)
            {
                _context.Blogs.Remove(blog);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
          return (_context.Blogs?.Any(e => e.BlogId == id)).GetValueOrDefault();
        }
    }
}

PROJECT_PRN211/Cake/Controllers/LoginController.cs
using Cake.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Web;

namespace Cake.Controllers
{
	public class LoginController : Controller
	{
		private readonly IHttpContextAccessor _contextSession;
		
		private readonly BakeryCakeContext _context;
//, IHttpContextAccessor httpContextAccessor
		public LoginController(BakeryCakeContext context)
		{
			_context = context;
			//_contextSession = httpContextAccessor;
		}
		public IHttpContextAccessor HttpContextAccessor { get; }
		public IActionResult Index()
		{
			return View();
		}
		public async Task<IActionResult> Login(string username, string pass)
		{
			var member1 = _context.Users
				.Include(x => x.Roles)
				.SingleOrDefault(u => u.UserName == username && u.Password == pass);
			if (member1 != null)
			{
				//_contextSession.HttpContext.Session.SetString("account", JsonConvert.SerializeObject(member1));
				return RedirectToAction("Index", "Home");
			}
			else
			{
				ViewData["fail"] = "Wrong username or pass";
				return View("Index");
			}
		}
		public IActionResult Email()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Email(string mail, string pass)
		{
			var member1 = _context.Users
				.Include(x => x.Roles)
				.SingleOrDefault(u => u.Mail == mail && u.Password == pass);
			if (member1 != null)
			{
				//_contextSession.HttpContext.Session.SetString("account", JsonConvert.SerializeObject(member1));
				return RedirectToAction("Index", "Home");
			}
			else
			{
				ViewData["fail"] = "Wrong email or pass";
				return View();
			}
		}
		public IActionResult Phone()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Phone(string phone, string pass)
		{
			var member1 = _context.Users
				.Include(x => x.Roles)
				.SingleOrDefault(u => u.Phone == phone && u.Password == pass);
			if (member1 != null)
			{
				//_contextSession.HttpContext.Session.SetString("account", JsonConvert.SerializeObject(member1));
				return RedirectToAction("Index", "Home");
			}
			else
			{
				ViewData["fail"] = "Wrong username or pass";
				return View("Index");
			}
		}
	}
}

PROJECT_PRN211/Cake/Controllers/MenuController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Cake.Controllers
{
    public class MenuController : Controller
    {
        // GET: MenuController
        public ActionResult Index()
        {
            return View();
        }

        // GET: MenuController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MenuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MenuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MenuController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MenuController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MenuController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MenuController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PROJECT_PRN211/Cake/Views/Shared/_Layout-Admin.cshtml
    <!DOCTYPE html>
    <html>

    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="~/assets/img/fav-icon.png" type="image/x-icon" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@ViewBag.Title</title>
    <!-- bootstrap 3.0.2 -->
    <link href="~/assets_Admin/css/bootstrap.min.css" rel="stylesheet" />
    <!-- font Awesome -->
    <link href="~/assets_Admin/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
    <link href="~/assets_Admin/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="~/assets_admin/css/morris/morris.css" rel="stylesheet" />
        <!-- jvectormap -->
    <link href="~/assets_Admin/css/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
        <!-- Date Picker -->
    <link href="~/assets_Admin/css/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
        <!-- fullCalendar -->
        <!-- <link href="css/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css" /> -->
        <!-- Daterange picker -->
    <link href="~/assets_Admin/css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
        <!-- iCheck for checkboxes and radio inputs -->
    <link href="~/assets_Admin/css/iCheck/all.css" rel="stylesheet" type="text/css" />
        <!-- bootstrap wysihtml5 - text editor -->
        <!-- <link href="css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" /> -->
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <!-- Theme style -->
    <link href="~/assets_admin/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet">
    </head>

    <body class="skin-black">
        <!-- header logo: style can be found in header.less -->
        <header class="header">
        <a href="index.html" class="logo">
            <img src="~/assets/img/logo-2.png" />
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span>Jane Doe <i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                                <li class="dropdown-header text-center">Account</li>

                                @*<li>
                                    <a href="#">
                                    <i class="fa fa-clock-o fa-fw pull-right"></i>
                                        <span class="badge badge-success pull-right">10</span> Updates</a>
                                    <a href="#">
                                    <i class="fa fa-envelope-o fa-fw pull-right"></i>
                                        <span class="badge badge-danger pull-right">5</span> Messages</a>
                                    <a href="#"><i class="fa fa-magnet fa-fw pull-right"></i>
                                        <span class="badge badge-info pull-right">3</span> Subscriptions</a>
                                    <a href="#"><i class="fa fa-question fa-fw pull-right"></i> <span class=
                                        "badge pull-right">11</span> FAQ</a>
                                </li>*@

                                <li class="divider"></li>

                                    <li>
                                        <a href="#">
                                        <i class="fa fa-user fa-fw pull-right"></i>
                                            Profile
                                        </a>
                                        <a data-toggle="modal" href="#modal-user-settings">
                                        <i class="fa fa-cog fa-fw pull-right"></i>
                                            Settings
                                        </a>
                                        </li>

                                        <li class="divider"></li>

                                        <li>
                                            <a href="#"><i class="fa fa-ban fa-fw pull-right"></i> Logout</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </nav>
        </header>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/assets_admin/img/1800.jpg" class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p>Hello, Jane</p>

                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <!-- search form -->
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search..." />
                            <span class="input-group-btn">
                                <button type='submit' name='seach' id='search-btn' class="btn btn-flat">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        <li class="active">
                            <a href="index.html">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <a href="general.html">
                                <i class="fa fa-gavel"></i> <span>General</span>
                            </a>
                        </li>

                        <li>
                            <a href="basic_form.html">
                                <i class="fa fa-globe"></i> <span>Basic Elements</span>
                            </a>
                        </li>

                        <li>
                            <a href="simple.html">
                                <i class="fa fa-glass"></i> <span>Simple tables</span>
                            </a>
                        </li>

                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>
            <aside class="right-side">
                @RenderBody()
            </aside>

        </div>


        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="~/assets_Admin/js/jquery.min.js" type="text/javascript"></script>

        <!-- jQuery UI 1.10.3 -->
    <script src="~/assets_Admin/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
        <!-- Bootstrap -->
    <script src="~/assets_Admin/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- daterangepicker -->
    <script src="~/assets_Admin/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>

    <script src="~/assets_Admin/js/plugins/chart.js" type="text/javascript"></script>

    <script src="~/assets_Admin/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
        <!-- calendar -->
    <script src="~/assets_Admin/js/plugins/fullcalendar/fullcalendar.js" type="text/javascript"></script>

        <!-- Director App -->
    <script src="~/assets_Admin/js/Director/app.js" type="text/javascript"></script>

        <!-- Director dashboard demo (This is only for demo purposes) -->
    <script src="~/assets_Admin/js/Director/dashboard.js" type="text/javascript"></script>

        
    </body>

</html>

PROJECT_PRN211/Cake/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="~/assets/img/fav-icon.png" type="image/x-icon" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@ViewBag.Title</title>

    <!-- Icon css link -->
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/assets/vendors/linearicons/style.css" rel="stylesheet">
    <link href="~/assets/vendors/flat-icon/flaticon.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">


    <!-- Rev slider css -->
    <link href="~/assets/vendors/revolution/css/settings.css" rel="stylesheet">
    <link href="~/assets/vendors/revolution/css/layers.css" rel="stylesheet">
    <link href="~/assets/vendors/revolution/css/navigation.css" rel="stylesheet">
    <link href="~/assets/vendors/animate-css/animate.css" rel="stylesheet">

    <!-- Extra plugin css -->
    <link href="~/assets/vendors/owl-carousel/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets/vendors/magnifc-popup/magnific-popup.css" rel="stylesheet">

    <link href="~/assets/css/style.css" rel="stylesheet">
    <link href="~/assets/css/responsive.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @* <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>*@
</head>
<body>

    <!--================Main Header Area =================-->
    <header class="main_header_area">
        <div class="top_header_area row m0">
            <div class="container">
                <div class="float-left">
                    <a href="tell:+18004567890"><i class="fa fa-phone" aria-hidden="true"></i> + (1800) 456 7890</a>
                    <a href="mainto:info@cakebakery.com"><i class="fa fa-envelope-o" aria-hidden="true"></i> info@cakebakery.com</a>
                </div>
                <div class="float-right">
                    <ul class="h_social list_style">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                    <ul class="h_search list_style">
                        <li class="shop_cart"><a href="#"><i class="lnr lnr-cart"></i></a></li>
                        <li><a class="popup-with-zoom-anim" href="#test-search"><i class="fa fa-search"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="main_menu_two">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="index.html"><img src="assets/img/logo-2.png" alt=""></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="my_toggle_menu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav justify-content-end">

                            <li><a asp-controller="Home" asp-action="Index">Home</a></li>

                            <li><a href="cake.html">Our Cakes</a></li>
                            <li><a asp-area="" asp-controller="Menu" asp-action="index">Menu</a></li>
                            
                            
                            <li><a asp-area="" asp-controller="Blogs" asp-action="index">Blog</a></li>
                            
                            <li><a asp-controller="" asp-action="Index" >Contact Us</a></li>
                            <li>
                                <a asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                            <li><a asp-controller="" asp-action="Index">Register</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <!--================End Main Header Area =================-->
    <div>
        @RenderBody()
    </div>
    <footer class="footer_area">
        <div class="footer_widgets">
            <div class="container">
                <div class="row footer_wd_inner">
                    <div class="col-lg-3 col-6">
                        <aside class="f_widget f_about_widget">
                            <img src="~/assets/img/footer-logo.png" alt="">
                            <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui bland itiis praesentium voluptatum deleniti atque corrupti.</p>
                            <ul class="nav">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </aside>
                    </div>
                    <div class="col-lg-3 col-6">
                        <aside class="f_widget f_link_widget">
                            <div class="f_title">
                                <h3>Quick links</h3>
                            </div>
                            <ul class="list_style">
                                <li><a href="#">Your Account</a></li>
                                <li><a href="#">View Order</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Terms & Conditionis</a></li>
                            </ul>
                        </aside>
                    </div>
                    <div class="col-lg-3 col-6">
                        <aside class="f_widget f_link_widget">
                            <div class="f_title">
                                <h3>Work Times</h3>
                            </div>
                            <ul class="list_style">
                                <li><a href="#">Mon. :  Fri.: 8 am - 8 pm</a></li>
                                <li><a href="#">Sat. : 9am - 4pm</a></li>
                                <li><a href="#">Sun. : Closed</a></li>
                            </ul>
                        </aside>
                    </div>
                    <div class="col-lg-3 col-6">
                        <aside class="f_widget f_contact_widget">
                            <div class="f_title">
                                <h3>Contact Info</h3>
                            </div>
                            <h4>(1800) 574 9687</h4>
                            <p>Justshiop Store <br />256, baker Street,, New Youk, 5245</p>
                            <h5>cakebakery@contact.co.in</h5>
                        </aside>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <!--================End Footer Area =================-->
    <!--================Search Box Area =================-->
    <div class="search_area zoom-anim-dialog mfp-hide" id="test-search">
        <div class="search_box_inner">
            <h3>Search</h3>
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button"><i class="icon icon-Search"></i></button>
                </span>
            </div>
        </div>
    </div>
    <!--================End Search Box Area =================-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/assets/js/jquery-3.2.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <!-- Rev slider js -->
    <script src="~/assets/vendors/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/assets/vendors/revolution/js/jquery.themepunch.revolution.min.js"></script>
    <script src="~/assets/vendors/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="~/assets/vendors/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script src="~/assets/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="~/assets/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="~/assets/vendors/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <!-- Extra plugin js -->
    <script src="~/assets/vendors/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/assets/vendors/magnifc-popup/jquery.magnific-popup.min.js"></script>
    <script src="~/assets/vendors/datetime-picker/js/moment.min.js"></script>
    <script src="~/assets/vendors/datetime-picker/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/assets/vendors/nice-select/js/jquery.nice-select.min.js"></script>
    <script src="~/assets/vendors/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/assets/vendors/lightbox/simpleLightbox.min.js"></script>

    <script src="~/assets/js/theme.js"></script>
</body>
</html>